-- change this to your team id
use ftp93;

-- comment this line for the very first time
drop table if exists EMPLOYEE;

-- create the table
create table EMPLOYEE (EMP_ID int ,
EMP_NAME varchar(50) NOT NULL,
EMP_EMAILID varchar(50) UNIQUE,
EMP_MOBILE_NUMBER BIGINT NOT NULL,
EMP_DATE_JOINED date NOT NULL,
EMP_DEPARTMENT VARCHAR(50) NOT NULL,
EMP_LEAVE_BALANCE INT,
EMP_MANAGER_ID INT,
CONSTRAINT EMPLOYEE_EMP_ID_PK PRIMARY KEY(EMP_ID));


create table LEAVE_DETAILS(EMP_ID int,
LVD_ID int,
LVD_NO_OF_DAYS int NOT NULL,
LVD_START_DATE date,
LVD_END_DATE date,
LVD_LEAVE_TYPE enum('EL') NOT NULL,
LVD_LEAVE_STATUS enum('A','D','P') default 'P',
LVD_REASON varchar(150) NOT NULL,
LVD_APPLIED_ON date,
LVD_MANAGER_COMMENTS varchar(150) NOT NULL,
CONSTRAINT LEAVE_DETAILS_LVD_ID_PK PRIMARY KEY(LVD_ID),
CONSTRAINT LEAVE_DETAILS_EMP_ID_FK FOREIGN KEY(EMP_ID) 
REFERENCES EMPLOYEE(EMP_ID));

DROP TABLE LEAVE_DETAILS;




